// front-end-react/src/app/pages/Home.js
import React from 'react'
import Base from '../components/Base'
import './Home.css'

const Home = () => {

  const navigateToTeacherPage = () => {
    window.location.href = "http://localhost:4200";
  }

  return (
    <Base>
      <div className="bootstrap-wrapper">
          <div className="container">
              <div style={{marginTop: '20px'}}>
                  <div className="col-md-11 offset-md-1 text-center">
                      <h4>Welcome to Student Section !! </h4>
                  </div>
                  <div className='submit-container' style={{marginTop: '20px'}}>
                    <div class='submit-bn' onClick={navigateToTeacherPage}>Go to Teacher Section</div>
                  </div>
              </div>
          </div>
      </div>
    </Base>
  )
}

export default Home

// front-end-angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit{

  constructor() {}

  ngOnInit(): void {}

  navigateToStudentPage() {
    window.location.href = "http://localhost:3000";
  }

}

<div class="bootstrap-wrapper">
    <div class="container">
        <div class="mt20">
            <div class="col-md-10 offset-md-1 text-center">
                <h1>Welcome to Teacher Section !! </h1>
            </div>
            <div class='submit-container'>
                <div class="submit-btn" (click)="navigateToStudentPage()">Go to Student Section</div>
              <!-- <a href="http://localhost:3000"><div class="submit">I am a Student</div></a> -->
            </div>
        </div>
    </div>
</div>
