// front-end-angular/src/app/pages/user/instructions/instructions.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { QuizService } from 'src/app/services/quiz.service';
import Swal from 'sweetalert2';

@Component({
	selector: 'app-instructions',
	templateUrl: './instructions.component.html',
	styleUrls: ['./instructions.component.css']
})
export class InstructionsComponent implements OnInit {

	quizId: any
	quizTitle: any
	quiz : any
	quizTimeHr = 0
	quizTimeMins = 0
	marksPerQuestion = 0

	constructor(private route: ActivatedRoute, private quizService : QuizService, private router : Router) {
		this.quizId = this.route.snapshot.params['quizId'];
		this.quizTitle = this.route.snapshot.params['title'];
	}

	ngOnInit(): void {
		
		this.quizService.viewQuiz(this.quizId).subscribe(
			{
				next : (data : any) => {
					//console.log("data", data);
					this.quiz = data;
					this.marksPerQuestion = parseFloat((this.quiz.maxMarks/this.quiz.numberOfQuestions).toFixed(2));
					this.quizTimeHr = Math.trunc( (this.quiz.numberOfQuestions*this.marksPerQuestion)/60 );
					this.quizTimeMins = Math.trunc( (this.quiz.numberOfQuestions*this.marksPerQuestion)%60 );
				},
				error : (error) => {
					Swal.fire("Error", "Error showing quiz instructions", 'error')
				}
			}
		);
	}

	startQuiz() {
		Swal.fire({
			title: 'Do you want to start the quiz ?',
			showCancelButton: true,
			confirmButtonText: 'Start',
			icon : 'info'
		  }).then((result) => {
			/* Read more about isConfirmed, isDenied below */
			if (result.isConfirmed) {
			  this.router.navigate(['/attempt-quiz/',this.quizId]);
			}
		})
	}

}

<div mat-subheader class="text-center"> 
    <span class="font-family font-bolder-larger font-color"> Instructions for taking the Quiz  </span>
</div>

<div class="bootstrap-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <mat-card class = "mt10 mb10 font-family font-color">
                    <mat-card-header>
                        <mat-card-title>
                            Read the instructions carefully before starting the quiz
                        </mat-card-title>
                        <!-- <mat-card-subtitle></mat-card-subtitle> -->
                    </mat-card-header>

                    <mat-card-content class="mt20 mb20">
                        <b class="font-bold-large">Quiz : {{ quizTitle }} </b>
                        <br>
                        <br>
                        <b>{{quiz.description}} </b>
                        <br><br>
                        <hr>
                        <br>
                        <b class="font-bold-large">Important Instructions</b>

                        <ul>
                            <li>This quiz is for practise only.</li>
                            <li>This quiz will submit automatically once the timer has ran out.</li>
                            <li>You can attempt the quiz any number of time.</li>
                            <li>There are <b> {{quiz.numberOfQuestions}}  questions </b> in this quiz.</li>
                            <li>Time for the quiz is <b> {{ quizTimeHr }} hours </b> and  <b> {{ quizTimeMins }} minutes.</b></li>
                            <li>Each question carries <b> {{ marksPerQuestion }} marks. </b></li>
                            <li>All questions are multiple choice questions</li>

                        </ul>
                        <hr>
                    </mat-card-content>

                    <mat-card-actions class="mb10" style="display: flex; justify-content: center; align-items: center;">
                        <button mat-raised-button color="primary" (click) = "startQuiz()"> Start Quiz</button>

                    </mat-card-actions>
                </mat-card>
            </div>
        </div>
    </div>
</div>

// front-end-react/src/app/pages/user/Instructions.jsx
import React , {useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom';
import Base from '../../components/Base';
import Sidebar from '../../components/Sidebar';
import { Card, CardHeader, CardContent, Typography, Button, Divider, List, ListItem } from '@mui/material';
import { getQuiz } from '../../services/quiz-service';
import './Instructions.css'

const Instructions = () => {

    const { quizId, quizTitle } = useParams();
    const [quiz, setQuiz] = useState([]);
    const [quizTime, setQuizTime] = useState({
        "hr" : 0,
        "min" : 0
    });
    const navigate = useNavigate();

    const handleStartQuiz = (quizId, quizTitle) => {
        // Add your logic for starting the quiz
        navigate(`/user/quiz/attempt-quiz/${quizId}/${quizTitle}`);

    };

    useEffect(() => {
        const fetchQuiz = async () => {
          try {
            const data = await getQuiz(quizId);
            setQuiz(data);
            console.log("quiz->",data.title);
            // setQuizTime({
            //     "hr": Math.floor((data.numberOfQuestions * 2) / 60),
            //     "min": Math.floor((data.numberOfQuestions * 2) % 60)
            // });
          } catch (error) {
            console.error(`Error fetching quiz - ${quizTitle}`, error);
          }
        };
    
        fetchQuiz();
      }, []);

      useEffect(()=>{
            setQuizTime({
                "hr": Math.floor((quiz.numberOfQuestions * 2) / 60),
                "min": Math.floor((quiz.numberOfQuestions * 2) % 60)
            });
      }, [quiz])

    return (
        <Base>
            <div class="row">
                <div class="col-md-2">
                    <Sidebar></Sidebar>
                </div>
                <div class="col-md-10">
                    <div class="text-center"> 
                        <span className='heading'> Instructions for taking the Quiz - {quizTitle} </span>
                    </div>

                    <div className="bootstrap-wrapper">
                        <div className="container">
                            <div className="row">
                                <div >
                                    <Card className="mt10 mb10 font-family font-color">
                                        <CardHeader title="Read the instructions carefully before starting the quiz" />
                                        <CardContent className="mt20 mb20">
                                            <Typography variant="h5" component="div">
                                                Quiz: {quizTitle}
                                            </Typography>
                                            <Typography variant="body1" component="div">
                                                {quiz.description}
                                            </Typography>
                                            <Divider style={{ backgroundColor: '#a429b5', height: '2px' }} />
                                            <Typography variant="h5" component="div">
                                                Important Instructions
                                            </Typography>
                                            <List>
                                                <ListItem>This quiz is for practice only.</ListItem>
                                                <ListItem>This quiz will submit automatically once the timer has run out.</ListItem>
                                                <ListItem>You can attempt the quiz any number of times.</ListItem>
                                                <ListItem>There are&nbsp;<b>{quiz.numberOfQuestions} questions</b>&nbsp;in this quiz.</ListItem>
                                                {quizTime.hr !== 0 ? (
                                                    <ListItem>Time for the quiz is&nbsp;<b>{quizTime.hr}&nbsp;hours</b> and&nbsp;<b>{quizTime.min}&nbsp;minutes.</b></ListItem>
                                                ) : (
                                                    <ListItem>Time for the quiz is&nbsp;<b>{quizTime.min}&nbsp;minutes.</b></ListItem>
                                                )}
                                                <ListItem>Total marks for the quiz:&nbsp;<b>{quiz.maxMarks}&nbsp;marks.</b></ListItem>
                                                <ListItem>All questions are multiple-choice questions.</ListItem>
                                            </List>
                                            <Divider style={{ backgroundColor: '#a429b5', height: '2px' }} />
                                        </CardContent>
                                        <div className='submit-container'>
						                    <div className='submit' onClick={() => handleStartQuiz(quiz.quizId, quiz.title)}>Start Quiz</div>
					                    </div>
                                    </Card>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Base>
    )
}

export default Instructions
