// front-end-react/src/app/pages/user/AttemptQuiz.jsx
import React, { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardActions,
  Button,
  Typography,
  Container,
  Grid,
  Radio,
  RadioGroup,
  FormControlLabel,
  Divider,
  CircularProgress,
} from "@mui/material";
import { Link, useNavigate, useParams } from "react-router-dom";
import { evaluateQuiz, getQuiz } from "../../services/quiz-service";
import Base from "../../components/Base";
import Sidebar from "../../components/Sidebar";
import './AttemptQuiz.css'
import { getUser } from "../../services/login-service";

const AttemptQuiz = () => {

  const { quizId, quizTitle } = useParams();
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [quizQuestions, setQuizQuestions] = useState([]);
  const [score, setScore] = useState(0);
  const [totalMarks, setTotalMarks] = useState(0);
  const [correctAnswers, setCorrectAnswers] = useState(0);
  const [attemptedQuestions, setAttemptedQuestions] = useState(0);
  const [totalQuestions, setTotalQuestions] = useState(0);
  const [quizDuration, setQuizDuration] = useState(0);
  const [remainingTime, setRemainingTime] = useState();
  const [quizAttemptData, setQuizAttemptData] = useState(undefined);
  const [intervalId, setIntervalId] = useState(undefined);

  const navigate = useNavigate();

  useEffect(() => {
	const fetchQuiz = async () => {
	  try {
		const data = await getQuiz(quizId);
		setQuizQuestions(data.questions);
		console.log("quizQuestions->",data);
		setTotalMarks(data.maxMarks);
		setTotalQuestions(data.numberOfQuestions);
		setRemainingTime(data.numberOfQuestions*2*10);
		setQuizDuration(data.numberOfQuestions*2*10);
	  } catch (error) {
		console.error(`Error fetching quiz - ${quizTitle}`, error);
	  }
	};

	fetchQuiz();
  }, []);

  useEffect(() => {
	const updateQuizAttemptData = async () => {
		setQuizAttemptData({
			"quizTitle" : quizTitle,
			"numberOfQuestions" : totalQuestions,
			"totalMarks" : totalMarks,
			"userName" : getUser().userName,
			"quizAttemptQuestions" : quizQuestions
		});
	};

	updateQuizAttemptData();
  }, [quizAttemptData]);

  useEffect(() => {
	const intervalId = setInterval(() => {
	  setRemainingTime((prevTime) => prevTime - 1);
	}, 1000);
  
	return () => {
	  clearInterval(intervalId);
	  // Add a condition to check if remainingTime is <= 0 and submit the quiz
	  if (remainingTime === 0) {
		submitQuiz();
	  }
	};
  }, [remainingTime]);

//   useEffect(() => {
// 	const id = setInterval(() => {
// 		setRemainingTime((prevTime) => prevTime - 1);
// 	}, 1000);
// 	setIntervalId(id);
//   }, []); 

//   useEffect(() => {
// 	if (remainingTime == 0) {
// 		submitQuiz();
// 		clearInterval(intervalId);
// 	}
//   }, [remainingTime]);

  const handleRadioChange = (questionIndex, selectedOption) => {
    const updatedQuestions = [...quizQuestions];
    updatedQuestions[questionIndex].answerGiven = selectedOption;
    setQuizQuestions(updatedQuestions);

  };

  const submitQuiz = () => {
    // Add your logic to calculate score, correctAnswers, and attemptedQuestions
    console.log("submitted question->", quizQuestions);
	if (!isSubmitted) {
		setIsSubmitted(true);
		evaluateQuiz(quizAttemptData)
			.then((data)=>{
				console.log("score->", data);
				setScore(parseFloat(Number(data['score']).toFixed(2)));
				setCorrectAnswers(data['correctAnswers'])
				setAttemptedQuestions(data['attemptedQuestions'])
			}).catch((error) => {
				console.log("error in evaluate quiz ");
			})
	}
  };

  const printPage = () => {
    // Add your logic to print the page
	window.print()
  };

  const handleHome = () => {
    // Add your logic to print the page
	navigate(`/user/dashboard`);
  };

  const getFormattedTime = () => {
    const minutes = Math.floor(remainingTime / 60);
    const seconds = remainingTime % 60;
    return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  };

  return (
    <div>
        {!isSubmitted && (
          <Grid container spacing={3} >
            {/* Instructions */}
            <Grid item xs={2}>
              <div className="text-center">
                <Typography variant="h5" gutterBottom fontWeight={"bold"}>
                  Instructions
                </Typography>
                <Card>
                  <CardContent>
                    <ul style={{ textAlign: "left" }}>
                      <li>
                        <strong>Do not open new tab</strong>
                      </li>
                      <br />
                      <li>
                        <strong>Do not reload the page</strong>
                      </li>
                      <br />
                      <li>
                        <strong>Do not right-click on the page</strong>
                      </li>
                    </ul>
                  </CardContent>
                </Card>
              </div>
            </Grid>

            {/* Questions */}
            <Grid item xs={8}>
				{quizQuestions && (
					<div className="text-center">
					<Typography variant="h5" gutterBottom fontWeight={"bold"}>
						Quiz - {quizTitle}
					</Typography>
					</div>
				)}

				{quizQuestions.map((quizQuestion, index) => (
					<Card key={index} className="mt10">
					<CardContent>
						<Typography variant="h6" gutterBottom fontWeight={"bold"}>
						Q{index + 1}) {quizQuestion.questionContent}
						</Typography>
						<br />

						<RadioGroup
						aria-label={`Question ${index + 1}`}
						name={`question${index + 1}`}
						value={quizQuestion.answerGiven} // Assuming you have a property to track the selected option
						onChange={(event) => handleRadioChange(index, event.target.value)}
						>
						{quizQuestion.options.map((option, i) => (
							<FormControlLabel
							key={i}
							value={option}
							control={<Radio />}
							label={option}
							/>
						))}
						</RadioGroup>
					</CardContent>
					</Card>
				))}
              <br />
              <hr />
              <br />
              	<div className="container text-center mt20 mb20" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
					<div className="submit-btn" onClick={submitQuiz}>
						Submit Quiz
					</div>
				</div>

            </Grid>

            {/* Progress */}
            <Grid item xs={2} className="text-center">
              <div>
                <Typography variant="h5" gutterBottom fontWeight={"bold"}>
                  Progress
                </Typography>

				<Card>
					<CardContent>
						<Typography variant="h6" gutterBottom>
							Time Remaining
						</Typography>
						<Divider style={{ backgroundColor: '#a429b5', height: '2px' }} />
						<Typography variant="h6" gutterBottom>
						{getFormattedTime()}
						</Typography>
						<br />
						<CircularProgress
						variant="determinate"
						value={(remainingTime / quizDuration) * 100}
						className="mt20"
						style={{ margin: 'auto', width: '100px', height: '100px' }}
						color="secondary"
						/>
					</CardContent>
				</Card>
              </div>
            </Grid>
          </Grid>
        )}

        {/* Show the result */}
        {isSubmitted && (

			<Base>
				<div class="row">
					<div class="col-md-2">
						<Sidebar></Sidebar>
					</div>
					<div class="col-md-10">

						<div className="text-center ">
							<div class="text-center"> 
								<span className='heading'> Quiz Result </span>
							</div>
						</div>

						<div className="row mt10">
							<div className="col-md-6 offset-md-3">
							<Card className="text-center mb20 mt20">
								<CardContent>
								<hr className="hr-divider" />
								<br />
								<Typography variant="h6" gutterBottom>
									Max Marks: {totalMarks}
								</Typography>
								<br />
								<Typography variant="h6" gutterBottom>
									Score: {score}
								</Typography>
								<br />
								<Typography variant="h6" gutterBottom>
									Correct Answers: {correctAnswers}
								</Typography>
								<br />
								<Typography variant="h6" gutterBottom>
									Questions Attempted: {attemptedQuestions}
								</Typography>
								<br />
								<hr className="hr-divider" />
								</CardContent>

								<CardActions>
								<div className='submit-container'>
									<div className='submit' onClick={printPage}>Print</div>
									<div className='submit' onClick={handleHome}>Home</div>	
								</div>
								</CardActions>
							</Card>
							</div>
						</div>

					</div>
				</div>
			</Base>

        )}
    </div>
  );
};

export default AttemptQuiz;

// front-end-angular/src/app/pages/user/attempt-quiz/attempt-quiz.component.ts
import { LocationStrategy } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { QuestionService } from 'src/app/services/question.service';
import Swal from 'sweetalert2';

@Component({
	selector: 'app-attempt-quiz',
	templateUrl: './attempt-quiz.component.html',
	styleUrls: ['./attempt-quiz.component.css']
})
export class AttemptQuizComponent implements OnInit {

	quizId = -1;
	quizQuestions: any

	//result variables
	score = 0;
	correctAnswers = 0;
	attemptedQuestions = 0;

	//quiz status variable
	isSubmitted = false;

	//quiz timer variable
	timer: any

	constructor(private locationStrategy: LocationStrategy, private route: ActivatedRoute,
		private questionService: QuestionService, private router: Router) { }

	ngOnInit(): void {
		this.preventBackNavigation();
		this.quizId = this.route.snapshot.params['quizId'];
		this.loadQuestionsForTest();

	}

	loadQuestionsForTest() {
		this.questionService.viewQuestionsOfQuizForTest(this.quizId).subscribe(
			{
				next: (data: any) => {
					this.quizQuestions = data;
					this.timer = this.quizQuestions.length * 1 * 60;
					// this.quizQuestions.forEach((quizQuestion: any) => {
					// 	quizQuestion['answerGiven'] = '';
					// });
					//console.log(this.quizQuestions);
					this.startTimer();

				},
				error: (error) => {
					Swal.fire("Error while loading quiz question in the Test")
				}
			}
		);
	}

	preventBackNavigation() {
		history.pushState(null, "", location.href);
		this.locationStrategy.onPopState(() => {
			history.pushState(null, "", location.href);
		})
	}

	submitQuiz() {
		Swal.fire({
			title: 'Do you want to submit the quiz?',
			showCancelButton: true,
			confirmButtonText: 'Submit',
			icon: 'question'
		}).then((result) => {
			/* Read more about isConfirmed, isDenied below */
			if (result.isConfirmed) {
				this.evaluateQuiz();
			}
		})
	}

	evaluateQuiz() {

		this.isSubmitted = true;

		//call to server to check quiz result
		this.questionService.evaluateQuiz(this.quizQuestions).subscribe(
			{
				next: (data: any) => {
					console.log("result : ", data);
					this.score = parseFloat(Number(data['score']).toFixed(2));
					this.correctAnswers = data['correctAnswers'];
					this.attemptedQuestions = data['attemptedQuestions']

				},
				error: (error) => {
					console.log("result error : ", error);

				}
			}
		);

		// Swal.fire('Submitted !', '', 'success');
		// this.isSubmitted = true;
		// // calculation
		// this.quizQuestions.forEach((quizQuestion: any) => {

		// 	if (quizQuestion.answerGiven.trim() != '') {
		// 		if (quizQuestion.answerGiven == quizQuestion.answer) {
		// 			this.correctAnswers++;
		// 			this.score += (this.quizQuestions[0].quiz.maxMarks / this.quizQuestions.length);
		// 			this.attemptedQuestions++;
		// 		}
		// 		else {
		// 			this.attemptedQuestions++;
		// 		}
		// 	}
		// });
		// this.score = parseFloat(this.score.toFixed(2));
		// console.log(" => attempted : ", this.attemptedQuestions);
		// console.log(" => correct ans : ", this.correctAnswers);
		// console.log(" => score : ", this.score);
	}

	startTimer() {
		let t = window.setInterval(() => {
			if (this.timer <= 0) {
				this.evaluateQuiz();
				clearInterval(t);
			}
			else {
				this.timer--;
			}
		}, 1000)
	}

	getFormattedTime() {
		let mm = Math.floor(this.timer / 60);
		let ss = this.timer - mm * 60;
		return `${mm} min : ${ss} sec`
	}

	printPage() {
		window.print();
	}

}

<div class="bootstrap-wrapper" style="width: 100%;" *ngIf = "!isSubmitted">
    <div>
        <div class="row font-family font-color">

            <div class="col-md-2 mt20" style="width: fit-content;">
                <!-- instructions -->
                <div class=" text-center">
                    <b class="font-bold-large"> Instructions </b>
                    <mat-card class="mt20" style="width: fit-content;">
                        <mat-card-content>
                            <ul style="text-align: left;">
                                <li> <b> Do not open new tab </b> </li>
                                <br>
                                <li> <b> Do not reload the page </b> </li>
                                <br>
                                <li> <b> Do not right click on the page </b> </li>
                            </ul>
                        </mat-card-content>
                    </mat-card> 
                </div>
            </div>

            <div class="col-md-8 mt20" style="width: fit-content;">
                <!-- questions -->
                <ng-container *ngIf = "quizQuestions">
                    <div class="text-center">
                        <b class = "mt20 font-bold-large"> Quiz - {{quizQuestions[0].quiz.title}} </b>
                    </div>
                </ng-container>

                <mat-card *ngFor = "let quizQuestion of quizQuestions; let i = index" class = "mt20">
                    <mat-card-content>

                        <b> Q{{i+1}}) 
                            <span [innerHTML] = "quizQuestion.content"></span>
                        </b>
                        <br><br>    
                        <hr>

                        <div class="row mt20">
                            <div class="col-md-6">
                                <input type="radio" [value] = "quizQuestion.optionOne" [name]="'answer_' + i" [(ngModel)] = "quizQuestion.answerGiven"> {{quizQuestion.optionOne}}
                            </div>
                        
                        
                            <div class="col-md-6">
                                <input type="radio" [value] = "quizQuestion.optionTwo" [name]="'answer_' + i" [(ngModel)] = "quizQuestion.answerGiven"> {{quizQuestion.optionTwo}}
                            </div>
                                            
                            <div class="col md-6 mt20">
                                <input type="radio" [value] = "quizQuestion.optionThree" [name]="'answer_' + i" [(ngModel)] = "quizQuestion.answerGiven"> {{quizQuestion.optionThree}}
                            </div>
                        
                       
                            <div class="col-md-6 mt20">
                                <input type="radio" [value] = "quizQuestion.optionFour" [name]="'answer_' + i" [(ngModel)] = "quizQuestion.answerGiven"> {{quizQuestion.optionFour}}
                            </div>
                        </div>
                    </mat-card-content>
                </mat-card>
                <br>
                <hr>
                <br>
                <div class="container text-center mt20 mb20">
                    <button mat-raised-button color="primary" (click) = "submitQuiz()"> Submit Quiz</button>
                </div>

            </div>

            <div class=" col-md-2 mt20 text-center" style="width: fit-content;">
                <!-- progress -->
                <div>
                    <b class="font-bold-large"> Progress </b>
                    <mat-card class="mt20" >

                        <mat-card-content >
                            <b class="text-center">{{getFormattedTime()}}</b>
                            <br> <br>
                            <mat-spinner
                                mode="determinate"
                                [value]="(timer/(quizQuestions.length*1*60))*100"
                                class="mt20"
                                style="margin: auto;">
                            </mat-spinner>
                        </mat-card-content>
                    </mat-card>
                </div>
            </div>
            
        </div>

    </div>
</div>

<!-- show the result -->
<div mat-subheader class="text-center mt20" *ngIf = "isSubmitted"> 
    <span class="font-family font-bolder-larger font-color"> Quiz Result  </span>
</div>


<div class="bootstrap-wrapper mt20" *ngIf = "isSubmitted">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <mat-card class="container text-center mb20 mt20" >
                <mat-card-content>

                    <hr class="hr-divider">
                    <br>
                    <b class="font-family font-color font-bolder-larger"> Score : {{score}} </b>
                    <br><br>
                    <b class="font-family font-color font-bolder-larger"> Correct Answers : {{correctAnswers}} </b>
                    <br><br>
                    <b class="font-family font-color font-bolder-larger"> Questions Attempted : {{attemptedQuestions}} </b>
                    <br><br>
                    <hr class="hr-divider">
                    
                </mat-card-content>

                <mat-card-actions>
                    <div class="container text-center mt10 mb10">
                        <button mat-raised-button color="primary" (click) = "printPage()"> Print </button>
                        <button mat-raised-button color="primary" [routerLink] = "['/user/quizzes',-1]" class="ml20"> Home </button>
                    </div>
                </mat-card-actions>

            </mat-card>
        </div>
    </div>
</div>
